export const RATING_COLUMN_KEYS = ['rating_total', 'rating_defense', 'rating_attack']

export const COLUMNS = [
  {
    key: 'team_name',
    label: 'Team',
    to_fixed: 0,
    hidden: false,
    align: 'left',
    tooltip: 'No description',
  },
  { key: 'play_style', label: 'Style', hidden: false, align: 'left', tooltip: 'No description' },
  {
    key: 'rating_total',
    label: 'Rating',
    to_fixed: 2,
    hidden: false,
    align: 'left',
    tooltip: 'No description',
  },
  {
    key: 'games_played',
    label: 'Played',
    hidden: false,
    align: 'right',
    tooltip: 'No description',
  },
  {
    key: 'rating_points',
    label: 'Points',
    to_fixed: 2,
    hidden: true,
    align: 'right',
    tooltip: 'No description',
  },
  { key: 'points', label: 'Points', hidden: false, align: 'right', tooltip: 'No description' },
  {
    key: 'expected_points',
    label: 'xPts',
    to_fixed: 2,
    hidden: false,
    align: 'right',
    tooltip: 'No description',
  },
  {
    key: 'rating_attack',
    label: 'Attack',
    to_fixed: 2,
    hidden: false,
    align: 'left',
    tooltip: 'No description',
  },
  { key: 'goals', label: 'G', hidden: false, align: 'right', tooltip: 'Goals scored' },
  { key: 'xg', label: 'xG', to_fixed: 2, hidden: false, align: 'right', tooltip: 'Expected goals' },
  {
    key: 'rating_defense',
    label: 'Defense',
    to_fixed: 2,
    hidden: false,
    align: 'left',
    tooltip: 'No description',
  },
  { key: 'ga', label: 'GA', hidden: false, align: 'right', tooltip: 'Goals against' },
  {
    key: 'xga',
    label: 'xGA',
    to_fixed: 2,
    hidden: false,
    align: 'right',
    tooltip: 'Expected goals against',
  },
  { key: 'shots', label: 'Shots', hidden: false, align: 'right', tooltip: 'Shots taken' },
  {
    key: 'shots_on_target',
    label: 'SOT',
    hidden: false,
    align: 'right',
    tooltip: 'Shots on target',
  },
  { key: 'shots_against', label: 'SA', hidden: false, align: 'right', tooltip: 'Shots against' },
  {
    key: 'shots_on_target_against',
    label: 'SOTA',
    hidden: false,
    align: 'right',
    tooltip: 'shots on target against',
  },
  {
    key: 'aggregated_deep',
    label: 'Total Deep',
    hidden: true,
    align: 'right',
    tooltip: 'Passes completed within an estimated 20 yards (18m) of goal (Crosses excluded).',
  },
  {
    key: 'deep_per_game',
    label: 'Deep',
    to_fixed: 1,
    hidden: false,
    align: 'right',
    tooltip: 'Passes completed within an estimated 20 yards (18m) of goal (Crosses excluded).',
  },
  {
    key: 'aggregated_ppda',
    label: 'Total PPDA',
    to_fixed: 2,
    hidden: true,
    align: 'right',
    tooltip: 'Passes allowed per defensive action in the opposition half.',
  },
  {
    key: 'ppda_per_game',
    label: 'PPDA',
    to_fixed: 2,
    hidden: false,
    align: 'right',
    tooltip: 'Passes allowed per defensive action in the opposition half.',
  },
]
